# This Dockerfile builds the final HoML Server image for CPU.
# It layers the HoML server code on top of a pre-built vLLM CPU base image.
FROM ghcr.io/wsmlby/homl-vllm-cpu-base:latest


# Set the working directory to homl_server
WORKDIR /app/homl_server


# Copy requirements.txt and install dependencies
COPY requirements.txt ./
RUN pip install -r requirements.txt

# ENV ACCELERATOR=CPU

# Copy our application source code
COPY ./homl_server ./
COPY ./homl_server ./homl_server
# COPY ./vllm_patches ./patches

# RUN cd /usr/local/lib/python3.12/dist-packages/vllm && patch -p1 < /app/patches/registry.patch


ARG HOML_SERVER_VERSION=dev
ENV HOML_SERVER_VERSION=$HOML_SERVER_VERSION

# Start the server directly from main.py
ENTRYPOINT ["python3", "-u", "main.py"]
