# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import daemon_pb2 as daemon__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in daemon_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DaemonStub(object):
    """The daemon service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartModel = channel.unary_unary(
                '/homl.Daemon/StartModel',
                request_serializer=daemon__pb2.StartModelRequest.SerializeToString,
                response_deserializer=daemon__pb2.StartModelResponse.FromString,
                _registered_method=True)
        self.StopModel = channel.unary_unary(
                '/homl.Daemon/StopModel',
                request_serializer=daemon__pb2.StopModelRequest.SerializeToString,
                response_deserializer=daemon__pb2.StopModelResponse.FromString,
                _registered_method=True)
        self.ListRunningModels = channel.unary_unary(
                '/homl.Daemon/ListRunningModels',
                request_serializer=daemon__pb2.ListRunningModelsRequest.SerializeToString,
                response_deserializer=daemon__pb2.ListRunningModelsResponse.FromString,
                _registered_method=True)
        self.PullModel = channel.unary_stream(
                '/homl.Daemon/PullModel',
                request_serializer=daemon__pb2.PullModelRequest.SerializeToString,
                response_deserializer=daemon__pb2.PullModelProgress.FromString,
                _registered_method=True)
        self.ListLocalModels = channel.unary_unary(
                '/homl.Daemon/ListLocalModels',
                request_serializer=daemon__pb2.ListLocalModelsRequest.SerializeToString,
                response_deserializer=daemon__pb2.ListLocalModelsResponse.FromString,
                _registered_method=True)
        self.Version = channel.unary_unary(
                '/homl.Daemon/Version',
                request_serializer=daemon__pb2.VersionRequest.SerializeToString,
                response_deserializer=daemon__pb2.VersionResponse.FromString,
                _registered_method=True)


class DaemonServicer(object):
    """The daemon service definition.
    """

    def StartModel(self, request, context):
        """Starts a model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopModel(self, request, context):
        """Stops a model.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListRunningModels(self, request, context):
        """Lists running models.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullModel(self, request, context):
        """Pulls a model from a registry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLocalModels(self, request, context):
        """Lists locally available models.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DaemonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartModel': grpc.unary_unary_rpc_method_handler(
                    servicer.StartModel,
                    request_deserializer=daemon__pb2.StartModelRequest.FromString,
                    response_serializer=daemon__pb2.StartModelResponse.SerializeToString,
            ),
            'StopModel': grpc.unary_unary_rpc_method_handler(
                    servicer.StopModel,
                    request_deserializer=daemon__pb2.StopModelRequest.FromString,
                    response_serializer=daemon__pb2.StopModelResponse.SerializeToString,
            ),
            'ListRunningModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListRunningModels,
                    request_deserializer=daemon__pb2.ListRunningModelsRequest.FromString,
                    response_serializer=daemon__pb2.ListRunningModelsResponse.SerializeToString,
            ),
            'PullModel': grpc.unary_stream_rpc_method_handler(
                    servicer.PullModel,
                    request_deserializer=daemon__pb2.PullModelRequest.FromString,
                    response_serializer=daemon__pb2.PullModelProgress.SerializeToString,
            ),
            'ListLocalModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLocalModels,
                    request_deserializer=daemon__pb2.ListLocalModelsRequest.FromString,
                    response_serializer=daemon__pb2.ListLocalModelsResponse.SerializeToString,
            ),
            'Version': grpc.unary_unary_rpc_method_handler(
                    servicer.Version,
                    request_deserializer=daemon__pb2.VersionRequest.FromString,
                    response_serializer=daemon__pb2.VersionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'homl.Daemon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('homl.Daemon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Daemon(object):
    """The daemon service definition.
    """

    @staticmethod
    def StartModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homl.Daemon/StartModel',
            daemon__pb2.StartModelRequest.SerializeToString,
            daemon__pb2.StartModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homl.Daemon/StopModel',
            daemon__pb2.StopModelRequest.SerializeToString,
            daemon__pb2.StopModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListRunningModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homl.Daemon/ListRunningModels',
            daemon__pb2.ListRunningModelsRequest.SerializeToString,
            daemon__pb2.ListRunningModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/homl.Daemon/PullModel',
            daemon__pb2.PullModelRequest.SerializeToString,
            daemon__pb2.PullModelProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLocalModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homl.Daemon/ListLocalModels',
            daemon__pb2.ListLocalModelsRequest.SerializeToString,
            daemon__pb2.ListLocalModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/homl.Daemon/Version',
            daemon__pb2.VersionRequest.SerializeToString,
            daemon__pb2.VersionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
